server:
  port: 80
spring:
  datasource:
    name: mysql_blog
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://118.89.48.248:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: wl123456
      connectionProperties: druid.stat.mergeSql=true;
      minIdle: 5
      validationQuery: SELECT 'x'
      useGlobalDataSourceStat: true
      initialSize: 5
      maxWait: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testOnBorrow: false
      testWhileIdle: true
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      maxActive: 20
  redis:
      host: 192.168.101.111
      port: 6379
      password: 123456
      timeout: 1000
      database: 0
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100

  mvc:
    view:
      prefix: /
      suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wmj.blog.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql

druid:
  stat:
    slowSqlMillis: 5000

debug:
  true

# ��ӡsql
logging:
  level:
     com.example.mapper : debug



